using Sai.DealAssistant.Domain.Entities;

namespace Sai.DealAssistant.Application.System.Seeding;

public partial class DatabaseSeeder
{
    public static IEnumerable<Deal> GetTestDeals()
    {
        var random = new Random(42); // Seed for deterministic results
        DateOnly RandomStartDate()
        {
            var daysAgo = random.Next(0, 3 * 365); // up to 3 years ago
            return DateOnly.FromDateTime(DateTime.Today.AddDays(-daysAgo));
        }

        List<Deal> result = new List<Deal>
        {
            new Deal
            {
                Name = "Acme Website Revamp",
                Company = "Acme",
                Description = "One-time website redesign and optimization",
                Url = "https://acme.example.com",
                AiSearchInfo = "website, redesign, SEO",
                AiBriefDescription = "Redesign front-end, improve conversion",
                Industry = "Marketing",
                Status = "Open",
                TypeId = 1,
                StateId = 1,
                StartDate = RandomStartDate()
            },
            new Deal
            {
                Name = "Contoso Monthly Support",
                Company = "Contoso",
                Description = "Ongoing monthly support subscription",
                Url = "https://contoso.example.com/support",
                AiSearchInfo = "support, subscription, SLA",
                AiBriefDescription = "Monthly support and maintenance",
                Industry = "IT Services",
                Status = "Active",
                TypeId = 2,
                StateId = 2,
                StartDate = RandomStartDate()
            },
            new Deal { Name = "Globex Research Collaboration", Company = "Globex", Description = "Long-term R&D partnership", Url = "https://globex.example.com", AiSearchInfo = "research, collaboration, R&D", AiBriefDescription = "Multi-year collaboration on new products", Industry = "Manufacturing", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Initech Prototype", Company = "Initech", Description = "Prototype development engagement", Url = "https://initech.example.com", AiSearchInfo = "prototype, MVP", AiBriefDescription = "Build MVP for product validation", Industry = "Software", Status = "Closed - Won", TypeId = 1, StateId = 5 },
            new Deal { Name = "Umbrella Maintenance", Company = "Umbrella", Description = "Periodic maintenance for legacy systems", Url = "https://umbrella.example.com", AiSearchInfo = "maintenance, legacy", AiBriefDescription = "Scheduled maintenance and updates", Industry = "Healthcare", Status = "Closed - Lost", TypeId = 2, StateId = 6 },
            new Deal { Name = "Stark Labs Integration", Company = "Stark Labs", Description = "Integration of 3rd party APIs", Url = "https://stark.example.com", AiSearchInfo = "integration, APIs", AiBriefDescription = "Integrate external services", Industry = "Engineering", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Quantum Analytics Pilot", Company = "Quantum Analytics", Description = "Short pilot to evaluate quantum-assisted analytics", Url = "https://quantum.example.com", AiSearchInfo = "quantum, analytics, pilot", AiBriefDescription = "Pilot analytics using quantum-inspired models", Industry = "Data Science", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "BlueSun Digital Transformation", Company = "BlueSun", Description = "Company-wide digital transformation program", Url = "https://bluesun.example.com", AiSearchInfo = "digital transformation, cloud, modernization", AiBriefDescription = "Platform migration and process automation", Industry = "Retail", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Greenfield Mobile App", Company = "Greenfield", Description = "Design and build a new mobile application", Url = "https://greenfield.example.com", AiSearchInfo = "mobile app, iOS, Android, UX", AiBriefDescription = "End-to-end mobile product development", Industry = "Fintech", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Helios Cloud Migration", Company = "Helios", Description = "Migrate legacy services to cloud infrastructure", Url = "https://helios.example.com", AiSearchInfo = "cloud migration, AWS, Azure, lift-and-shift", AiBriefDescription = "Rehost and optimize services in cloud", Industry = "Telecom", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Apex Security Assessment", Company = "Apex", Description = "Comprehensive security audit and remediation plan", Url = "https://apex.example.com", AiSearchInfo = "security, audit, pentest", AiBriefDescription = "Identify vulnerabilities and remediation", Industry = "Banking", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Vertex AI Chatbot", Company = "Vertex", Description = "AI chatbot for customer support automation", Url = "https://vertex.example.com", AiSearchInfo = "chatbot, ai, nlp, support", AiBriefDescription = "Conversational assistant for support workflows", Industry = "Customer Service", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Orion Data Warehouse", Company = "Orion", Description = "Build centralized data warehouse and ETL pipelines", Url = "https://orion.example.com", AiSearchInfo = "data warehouse, ETL, analytics", AiBriefDescription = "Centralize analytics-ready data", Industry = "Analytics", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Nimbus IoT Deployment", Company = "Nimbus", Description = "Deploy IoT sensors and backend for monitoring", Url = "https://nimbus.example.com", AiSearchInfo = "IoT, sensors, telemetry", AiBriefDescription = "Edge devices with cloud telemetry", Industry = "Manufacturing", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Cascade Accessibility Upgrade", Company = "Cascade", Description = "Improve accessibility across web properties", Url = "https://cascade.example.com", AiSearchInfo = "accessibility, WCAG, a11y", AiBriefDescription = "Make websites accessible to all users", Industry = "Public Sector", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Atlas Localization Program", Company = "Atlas", Description = "Localization of product for APAC markets", Url = "https://atlas.example.com", AiSearchInfo = "localization, i18n, translations", AiBriefDescription = "Localization, compliance, and regional launch", Industry = "Software", Status = "Active", TypeId = 3, StateId = 2 },

            // 100 additional realistic deals
            new Deal { Name = "SolarGrid Pilot", Company = "SolarGrid", Description = "Pilot deployment of distributed solar monitoring", Url = "https://solargird.example.com", AiSearchInfo = "solar, IoT, monitoring", AiBriefDescription = "Edge monitoring for microgrids", Industry = "Energy", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Healthcare Portal Modernization", Company = "HealthPortal", Description = "Replace legacy patient portal with modern UX", Url = "https://healthportal.example.com", AiSearchInfo = "patient portal, modernization", AiBriefDescription = "Improve patient experience", Industry = "Healthcare", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "SmartRetail POS Integration", Company = "SmartRetail", Description = "Integrate POS systems with central analytics", Url = "https://smartretail.example.com", AiSearchInfo = "POS, analytics, retail", AiBriefDescription = "Real-time sales aggregation", Industry = "Retail", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Fleet Telematics Rollout", Company = "FleetTelematics", Description = "Fleet tracking and route optimization", Url = "https://fleettele.example.com", AiSearchInfo = "fleet, telematics, routing", AiBriefDescription = "Reduce fuel and idle time", Industry = "Logistics", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Banking KYC Automation", Company = "KYC Bank", Description = "Automate KYC checks using ML", Url = "https://kycbank.example.com", AiSearchInfo = "KYC, AML, ML", AiBriefDescription = "Reduce manual reviews", Industry = "Banking", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Retail Loyalty Platform", Company = "Loyalty Retail", Description = "Design loyalty and rewards platform", Url = "https://loyalty.example.com", AiSearchInfo = "loyalty, rewards, retail", AiBriefDescription = "Improve customer retention", Industry = "Retail", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Clinical Trial Data Hub", Company = "CT Data", Description = "Centralize clinical trial datasets for analysis", Url = "https://ctdata.example.com", AiSearchInfo = "clinical, trials, data", AiBriefDescription = "Secure data lake for trials", Industry = "Pharma", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Electric Bus Charging Network", Company = "E-Bus Charge", Description = "Install and manage charging stations", Url = "https://ebuscharge.example.com", AiSearchInfo = "ev, charging, transport", AiBriefDescription = "Deployment across city routes", Industry = "Transport", Status = "Closed - Won", TypeId = 1, StateId = 5 },
            new Deal { Name = "InsurTech Claims Automation", Company = "InsurTech", Description = "Auto-classify and route claims", Url = "https://insurclaims.example.com", AiSearchInfo = "claims, automation, insurtech", AiBriefDescription = "Faster claims resolution", Industry = "Insurance", Status = "Closed - Lost", TypeId = 2, StateId = 6 },
            new Deal { Name = "Edge Analytics for Factories", Company = "EdgeAnalytics", Description = "Real-time OEE monitoring at the edge", Url = "https://edgeoee.example.com", AiSearchInfo = "edge, OEE, manufacturing", AiBriefDescription = "Improve production uptime", Industry = "Manufacturing", Status = "Active", TypeId = 2, StateId = 3 },

            new Deal { Name = "Campus WiFi Upgrade", Company = "CampusWiFi", Description = "Upgrade campus WiFi to WiFi 6", Url = "https://campuswifi.example.com", AiSearchInfo = "wifi6, network", AiBriefDescription = "Better throughput and density", Industry = "Education", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Subscription Billing System", Company = "BillSub", Description = "Implement SaaS billing and invoicing", Url = "https://billsub.example.com", AiSearchInfo = "billing, subscription", AiBriefDescription = "Recurring billing platform", Industry = "SaaS", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "AI-Powered QA Automation", Company = "AIQA", Description = "Automate QA using AI test generation", Url = "https://aiqa.example.com", AiSearchInfo = "QA, AI, testing", AiBriefDescription = "Reduce regression testing time", Industry = "Software", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Smart Meter Rollout", Company = "SmartMeter", Description = "Deploy smart electricity meters", Url = "https://smartmeter.example.com", AiSearchInfo = "smartmeter, utilities", AiBriefDescription = "Two-way metering and analytics", Industry = "Energy", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Voice Commerce Assistant", Company = "VoiceCommerce", Description = "Voice assistant integration for purchases", Url = "https://voicecommerce.example.com", AiSearchInfo = "voice, commerce, assistant", AiBriefDescription = "Hands-free shopping flow", Industry = "E-commerce", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Warehouse Robotics Proof", Company = "RobotPick", Description = "Proof-of-concept for warehouse picking robots", Url = "https://robotpick.example.com", AiSearchInfo = "robotics, warehouse", AiBriefDescription = "Reduce pick time", Industry = "Logistics", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Regulatory Reporting Engine", Company = "RegReport", Description = "Automate regulatory filings", Url = "https://regreport.example.com", AiSearchInfo = "compliance, reporting", AiBriefDescription = "Reduce manual compliance effort", Industry = "Finance", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Personalized Marketing Platform", Company = "Personalize", Description = "Real-time personalization for e-commerce", Url = "https://personalize.example.com", AiSearchInfo = "personalization, marketing", AiBriefDescription = "Increase conversion via personalization", Industry = "Retail", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Onboard Analytics for EVs", Company = "EVAnalytics", Description = "In-vehicle telematics analytics", Url = "https://evanalytics.example.com", AiSearchInfo = "EV, telematics", AiBriefDescription = "Battery and route analytics", Industry = "Automotive", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Document OCR Service", Company = "DocOCR", Description = "High-accuracy OCR pipeline", Url = "https://dococr.example.com", AiSearchInfo = "OCR, document", AiBriefDescription = "Automate document ingestion", Industry = "Professional Services", Status = "Open", TypeId = 1, StateId = 1 },

            new Deal { Name = "Connected Farm Sensors", Company = "FarmConnect", Description = "IoT sensors and analytics for farms", Url = "https://farmconnect.example.com", AiSearchInfo = "agri, IoT", AiBriefDescription = "Optimize water and yield", Industry = "Agriculture", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Digital Twin Platform", Company = "DTwin", Description = "Digital twin for manufacturing lines", Url = "https://dtwin.example.com", AiSearchInfo = "digital twin, manufacturing", AiBriefDescription = "Simulate production scenarios", Industry = "Manufacturing", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Marketplace Integration", Company = "MarketConnect", Description = "Connect product catalog to marketplaces", Url = "https://marketconnect.example.com", AiSearchInfo = "marketplace, integration", AiBriefDescription = "Sync inventory and listings", Industry = "E-commerce", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Employee Benefits Portal", Company = "Benefits", Description = "Self-service benefits enrollment", Url = "https://benefits.example.com", AiSearchInfo = "HR, benefits", AiBriefDescription = "Streamline enrollment and changes", Industry = "Human Resources", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Supply Chain Visibility", Company = "SCVisibility", Description = "End-to-end shipment visibility platform", Url = "https://scvisibility.example.com", AiSearchInfo = "supply chain, visibility", AiBriefDescription = "Track shipments and exceptions", Industry = "Logistics", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Microservices Replatform", Company = "MicroReplatform", Description = "Replatform monolith to microservices", Url = "https://microreplatform.example.com", AiSearchInfo = "microservices, replatform", AiBriefDescription = "Increase deployment velocity", Industry = "Software", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Smart Building Energy", Company = "SmartBuilding", Description = "Energy optimization for office buildings", Url = "https://smartbuilding.example.com", AiSearchInfo = "energy, building", AiBriefDescription = "Reduce HVAC energy use", Industry = "Real Estate", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Pharma Supply Cold Chain", Company = "ColdChain", Description = "Cold chain monitoring for pharmaceuticals", Url = "https://coldchain.example.com", AiSearchInfo = "cold chain, pharma", AiBriefDescription = "Ensure integrity during transit", Industry = "Pharma", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Local Government CRM", Company = "GovCRM", Description = "Citizen services CRM deployment", Url = "https://govcrm.example.com", AiSearchInfo = "CRM, government", AiBriefDescription = "Streamline citizen requests", Industry = "Public Sector", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "AI Hiring Assistant", Company = "AIHire", Description = "Automate resume screening and interview scheduling", Url = "https://aihire.example.com", AiSearchInfo = "hiring, AI", AiBriefDescription = "Speed up recruitment", Industry = "HR Tech", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Cross-Border Payments", Company = "CrossPay", Description = "Implement low-cost cross-border payment rails", Url = "https://crosspay.example.com", AiSearchInfo = "payments, fintech", AiBriefDescription = "Reduce remittance fees", Industry = "Fintech", Status = "Closed - Won", TypeId = 3, StateId = 5 },

            new Deal { Name = "Smart City Parking", Company = "SmartPark", Description = "Real-time parking availability platform", Url = "https://smartpark.example.com", AiSearchInfo = "parking, smartcity", AiBriefDescription = "Reduce traffic and search time", Industry = "Transport", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Enterprise Search Upgrade", Company = "EntSearch", Description = "Replace search engine for enterprise data", Url = "https://entsearch.example.com", AiSearchInfo = "search, enterprise", AiBriefDescription = "Faster internal search", Industry = "Software", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Customer Data Platform", Company = "CDP", Description = "Centralize customer profiles for marketing", Url = "https://cdp.example.com", AiSearchInfo = "CDP, marketing", AiBriefDescription = "Unified customer view", Industry = "Retail", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Video Streaming Optimization", Company = "StreamOpt", Description = "Reduce CDN cost and latency", Url = "https://streamopt.example.com", AiSearchInfo = "video, CDN", AiBriefDescription = "Adaptive bitrate optimization", Industry = "Media", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "SaaS Onboarding Automation", Company = "Onboard", Description = "Automate user onboarding and activation", Url = "https://onboard.example.com", AiSearchInfo = "onboarding, SaaS", AiBriefDescription = "Increase activation metrics", Industry = "SaaS", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Retail Checkout Kiosk", Company = "CheckoutKiosk", Description = "Self-service checkout kiosk pilot", Url = "https://checkoutkiosk.example.com", AiSearchInfo = "kiosk, retail", AiBriefDescription = "Reduce queue times", Industry = "Retail", Status = "Closed - Lost", TypeId = 1, StateId = 6 },
            new Deal { Name = "Smart Grid Forecasting", Company = "GridForecast", Description = "Demand forecasting for utility grid", Url = "https://gridforecast.example.com", AiSearchInfo = "forecasting, utility", AiBriefDescription = "Improve dispatch decisions", Industry = "Energy", Status = "In Progress", TypeId = 3, StateId = 3 },
            new Deal { Name = "Telemedicine Platform", Company = "Telemed", Description = "Telemedicine rollout with integrated EMR", Url = "https://telemed.example.com", AiSearchInfo = "telemedicine, EMR", AiBriefDescription = "Remote consultations and records", Industry = "Healthcare", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Fraud Detection Service", Company = "FraudScore", Description = "Real-time fraud scoring for transactions", Url = "https://fraudscore.example.com", AiSearchInfo = "fraud, scoring", AiBriefDescription = "Detect anomalous behavior", Industry = "Finance", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Interactive Voice Response Revamp", Company = "IVRNLP", Description = "Modernize IVR with natural language", Url = "https://ivrnlp.example.com", AiSearchInfo = "IVR, nlp", AiBriefDescription = "Better self-service via voice", Industry = "Customer Service", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Robotic Process Automation (RPA)", Company = "RPA", Description = "RPA deployment for back-office tasks", Url = "https://rpa.example.com", AiSearchInfo = "RPA, automation", AiBriefDescription = "Automate repetitive tasks", Industry = "Professional Services", Status = "Closed - Won", TypeId = 2, StateId = 5 },

            new Deal { Name = "API Rate Limiting Platform", Company = "APIGate", Description = "Centralized API gateway with rate limiting", Url = "https://apigate.example.com", AiSearchInfo = "api, gateway", AiBriefDescription = "Protect backend resources", Industry = "Software", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Next-Gen POS Analytics", Company = "POSAnalytics", Description = "POS-level analytics and anomaly detection", Url = "https://posanalytics.example.com", AiSearchInfo = "POS, analytics", AiBriefDescription = "Detect abnormal transactions", Industry = "Retail", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Hybrid Cloud Backup", Company = "HybridBackup", Description = "Implement hybrid cloud backup and DR", Url = "https://hybridbackup.example.com", AiSearchInfo = "backup, DR", AiBriefDescription = "Reliable backups and fast recovery", Industry = "IT Services", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Precision Agriculture Platform", Company = "Agri-Precision", Description = "Satellite imagery analytics for crop yield", Url = "https://agri-precision.example.com", AiSearchInfo = "agri, satellite", AiBriefDescription = "Improve yield predictions", Industry = "Agriculture", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Mobile Wallet Launch", Company = "MobileWallet", Description = "Launch mobile wallet with NFC payments", Url = "https://mobilewallet.example.com", AiSearchInfo = "wallet, nfc", AiBriefDescription = "Enable contactless payments", Industry = "Fintech", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "3D Printing Production Line", Company = "3DManufacture", Description = "Scale additive manufacturing for parts", Url = "https://3dmanufacture.example.com", AiSearchInfo = "3d printing, manufacturing", AiBriefDescription = "Rapid production of custom parts", Industry = "Manufacturing", Status = "Proposal", TypeId = 3, StateId = 4 },
            new Deal { Name = "Cloud Cost Optimization", Company = "CloudCost", Description = "Right-size cloud spend across accounts", Url = "https://cloudcost.example.com", AiSearchInfo = "cloud, optimization", AiBriefDescription = "Reduce monthly cloud bill", Industry = "SaaS", Status = "Closed - Won", TypeId = 1, StateId = 5 },
            new Deal { Name = "Digital Payment Kiosk", Company = "PayKiosk", Description = "Self-serve payment kiosks for transit", Url = "https://paykiosk.example.com", AiSearchInfo = "kiosk, transit", AiBriefDescription = "Increase ticketing throughput", Industry = "Transport", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "EHR Interoperability Project", Company = "EHRConnect", Description = "Connect EHR systems across clinics", Url = "https://ehrconnect.example.com", AiSearchInfo = "EHR, interoperability", AiBriefDescription = "Share clinical records securely", Industry = "Healthcare", Status = "In Progress", TypeId = 3, StateId = 3 },
            new Deal { Name = "Connected Home Security", Company = "HomeSecure", Description = "Smart home security system rollout", Url = "https://homesecure.example.com", AiSearchInfo = "IoT, security", AiBriefDescription = "Connected sensors and monitoring", Industry = "Consumer", Status = "Open", TypeId = 1, StateId = 1 },

            new Deal { Name = "Smart Lighting Retrofit", Company = "SmartLight", Description = "LED and smart controls retrofitting", Url = "https://smartlight.example.com", AiSearchInfo = "lighting, retrofit", AiBriefDescription = "Energy and maintenance savings", Industry = "Real Estate", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Automated Tax Filing", Company = "TaxTool", Description = "Prepare and submit tax filings automatically", Url = "https://taxtool.example.com", AiSearchInfo = "tax, automation", AiBriefDescription = "Reduce manual tax work", Industry = "Finance", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Augmented Reality Retail", Company = "ARRetail", Description = "AR try-on feature for online store", Url = "https://arretail.example.com", AiSearchInfo = "AR, retail", AiBriefDescription = "Improve online conversion", Industry = "E-commerce", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Voice-of-Customer Analytics", Company = "VOC", Description = "Analyze customer feedback with NLP", Url = "https://voc.example.com", AiSearchInfo = "nlp, feedback", AiBriefDescription = "Extract sentiment and themes", Industry = "Customer Service", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Hybrid Workplace Platform", Company = "HybridWork", Description = "Collaboration tools for hybrid teams", Url = "https://hybridwork.example.com", AiSearchInfo = "collaboration, workplace", AiBriefDescription = "Improve remote productivity", Industry = "Professional Services", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Blockchain Supply Trace", Company = "BlockTrace", Description = "Immutable supply chain tracing pilot", Url = "https://blocktrace.example.com", AiSearchInfo = "blockchain, supply chain", AiBriefDescription = "Trace provenance of goods", Industry = "Logistics", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Digital ID Program", Company = "DigitalID", Description = "National digital ID pilot", Url = "https://digitalid.example.com", AiSearchInfo = "identity, government", AiBriefDescription = "Secure digital identity", Industry = "Public Sector", Status = "Closed - Won", TypeId = 1, StateId = 5 },
            new Deal { Name = "Customer Onboarding Kiosk", Company = "BranchKiosk", Description = "In-branch self-service kiosks", Url = "https://branchkiosk.example.com", AiSearchInfo = "kiosk, onboarding", AiBriefDescription = "Reduce branch staffing needs", Industry = "Banking", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Predictive Maintenance Service", Company = "PredictMaint", Description = "Predict failures for heavy equipment", Url = "https://predictmaint.example.com", AiSearchInfo = "predictive, maintenance", AiBriefDescription = "Lower unplanned downtime", Industry = "Manufacturing", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Next-Gen Learning Platform", Company = "LearnPlatform", Description = "Adaptive learning for corporate training", Url = "https://learnplatform.example.com", AiSearchInfo = "learning, adaptive", AiBriefDescription = "Personalized learning paths", Industry = "Education", Status = "Proposal", TypeId = 1, StateId = 4 },

            new Deal { Name = "Microgrid Finance Program", Company = "MicrogridFinance", Description = "Finance model for community microgrids", Url = "https://microgridfinance.example.com", AiSearchInfo = "microgrid, finance", AiBriefDescription = "Enable small-scale renewables", Industry = "Energy", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "AI Legal Assistant", Company = "AILegal", Description = "Automate legal research and document drafting", Url = "https://ailegal.example.com", AiSearchInfo = "legal, AI", AiBriefDescription = "Accelerate legal workflows", Industry = "Legal", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "B2B Market Intelligence", Company = "B2BIntel", Description = "Competitive intelligence for sales teams", Url = "https://b2bintel.example.com", AiSearchInfo = "intel, b2b", AiBriefDescription = "Actionable competitor insights", Industry = "Professional Services", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Connected Clinic Kiosk", Company = "ClinicKiosk", Description = "Patient check-in kiosk integrated with EHR", Url = "https://clinickiosk.example.com", AiSearchInfo = "clinic, kiosk", AiBriefDescription = "Reduce front-desk load", Industry = "Healthcare", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "High-Performance CDN", Company = "HPCDN", Description = "Global CDN optimization and caching", Url = "https://hpcdn.example.com", AiSearchInfo = "CDN, performance", AiBriefDescription = "Lower latency for global users", Industry = "Media", Status = "Negotiation", TypeId = 1, StateId = 4 },
            new Deal { Name = "Privacy Compliance Toolkit", Company = "PrivacyToolkit", Description = "Automated privacy policy and consent management", Url = "https://privacytoolkit.example.com", AiSearchInfo = "privacy, compliance", AiBriefDescription = "Manage user consent at scale", Industry = "Software", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Autonomous Drone Delivery POC", Company = "DroneDelivery", Description = "Proof-of-concept for last-mile drone delivery", Url = "https://dronedelivery.example.com", AiSearchInfo = "drone, delivery", AiBriefDescription = "Automate last-mile logistics", Industry = "Logistics", Status = "Proposal", TypeId = 3, StateId = 4 },
            new Deal { Name = "Digital Twin for Buildings", Company = "DTBuildings", Description = "Energy and occupancy optimization digital twin", Url = "https://dtbuildings.example.com", AiSearchInfo = "digital twin, buildings", AiBriefDescription = "Reduce operational costs", Industry = "Real Estate", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Automated Collections Workflow", Company = "Collections", Description = "Collections automation for receivables", Url = "https://collections.example.com", AiSearchInfo = "collections, automation", AiBriefDescription = "Improve recovery rates", Industry = "Finance", Status = "Closed - Won", TypeId = 2, StateId = 5 },
            new Deal { Name = "Smart Waste Management", Company = "SmartWaste", Description = "Sensor-based waste pickup optimization", Url = "https://smartwaste.example.com", AiSearchInfo = "waste, IoT", AiBriefDescription = "Optimize pickup routes", Industry = "Public Sector", Status = "In Progress", TypeId = 3, StateId = 3 },

            new Deal { Name = "Content Moderation API", Company = "Moderate", Description = "Automated moderation for user-generated content", Url = "https://moderate.example.com", AiSearchInfo = "moderation, ml", AiBriefDescription = "Keep community safe", Industry = "Media", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Warehouse Slotting Optimization", Company = "SlotOpt", Description = "Optimize storage layout using ML", Url = "https://slotopt.example.com", AiSearchInfo = "warehouse, optimization", AiBriefDescription = "Improve picking efficiency", Industry = "Logistics", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Smart Meter Billing Integration", Company = "MeterBill", Description = "Integrate smart meters with billing", Url = "https://meterbill.example.com", AiSearchInfo = "meter, billing", AiBriefDescription = "Automate consumption billing", Industry = "Energy", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Conversational IVR Analytics", Company = "IVRAnalytics", Description = "Analytics for IVR voice interactions", Url = "https://ivranalytics.example.com", AiSearchInfo = "ivr, analytics", AiBriefDescription = "Improve self-service flows", Industry = "Customer Service", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Virtual Event Platform", Company = "VirtualEvent", Description = "Platform for hosting interactive virtual events", Url = "https://virtualevent.example.com", AiSearchInfo = "virtual events, platform", AiBriefDescription = "Scale online events", Industry = "Media", Status = "In Progress", TypeId = 3, StateId = 3 },
            new Deal { Name = "Retail Inventory Forecasting", Company = "InvForecast", Description = "Demand forecasting for seasonal products", Url = "https://invforecast.example.com", AiSearchInfo = "forecasting, retail", AiBriefDescription = "Reduce stockouts and overstocks", Industry = "Retail", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Enterprise Backup Archival", Company = "Archive", Description = "Long-term archive solution for backups", Url = "https://archive.example.com", AiSearchInfo = "archive, backup", AiBriefDescription = "Compliant long-term storage", Industry = "IT Services", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Smart Meter Analytics", Company = "MeterAnalytics", Description = "Usage pattern analytics and alerts", Url = "https://meteranalytics.example.com", AiSearchInfo = "analytics, energy", AiBriefDescription = "Detect anomalies in consumption", Industry = "Energy", Status = "Closed - Won", TypeId = 1, StateId = 5 },
            new Deal { Name = "Mobile Health Monitoring", Company = "MHealth", Description = "Remote patient monitoring using mobile app", Url = "https://mhealth.example.com", AiSearchInfo = "mhealth, monitoring", AiBriefDescription = "Continuous vitals monitoring", Industry = "Healthcare", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Smart Vendor Onboarding", Company = "VendorOnboard", Description = "Automate supplier onboarding and KYC", Url = "https://vendoronboard.example.com", AiSearchInfo = "onboarding, vendor", AiBriefDescription = "Faster vendor activation", Industry = "Procurement", Status = "Proposal", TypeId = 1, StateId = 4 },

            new Deal { Name = "Renewable PPA Platform", Company = "PPA", Description = "Platform for managing PPAs with renewable generators", Url = "https://ppa.example.com", AiSearchInfo = "ppa, renewable", AiBriefDescription = "Manage contract terms and settlements", Industry = "Energy", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Smart Tourism App", Company = "SmartTour", Description = "Personalized travel and itinerary recommendations", Url = "https://smarttour.example.com", AiSearchInfo = "tourism, recommendations", AiBriefDescription = "Localized travel experiences", Industry = "Hospitality", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Data Privacy Audit", Company = "PrivacyAudit", Description = "Third-party privacy and security audit", Url = "https://privacyaudit.example.com", AiSearchInfo = "privacy, audit", AiBriefDescription = "Gap analysis and remediation plan", Industry = "Professional Services", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Edge Video Analytics", Company = "EdgeVideo", Description = "Real-time video analytics on edge devices", Url = "https://edgevideo.example.com", AiSearchInfo = "video, edge, analytics", AiBriefDescription = "Reduce bandwidth by processing locally", Industry = "Security", Status = "In Progress", TypeId = 3, StateId = 3 },
            new Deal { Name = "Green Building Certification", Company = "GreenBuild", Description = "Consulting and retrofit for green certification", Url = "https://greenbuild.example.com", AiSearchInfo = "green, certification", AiBriefDescription = "Meet sustainability standards", Industry = "Real Estate", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Smart Inventory Replenishment", Company = "Replenish", Description = "Automated reorder triggers using ML", Url = "https://replenish.example.com", AiSearchInfo = "inventory, ml", AiBriefDescription = "Keep optimal stock levels", Industry = "Retail", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Contact Center Workforce AI", Company = "WorkforceAI", Description = "Forecast staffing and automate scheduling", Url = "https://workforceai.example.com", AiSearchInfo = "workforce, AI", AiBriefDescription = "Optimize agent availability", Industry = "Customer Service", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Autonomous Vehicle Simulation", Company = "AVSim", Description = "Simulation environment for AV testing", Url = "https://avsim.example.com", AiSearchInfo = "autonomous, simulation", AiBriefDescription = "Test edge cases safely", Industry = "Automotive", Status = "Closed - Won", TypeId = 3, StateId = 5 },
            new Deal { Name = "API Monetization Platform", Company = "APIMonetize", Description = "Monetize APIs with metering and billing", Url = "https://apimonetize.example.com", AiSearchInfo = "api, monetize", AiBriefDescription = "Charge for API usage", Industry = "Software", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Telematics Insurance Offering", Company = "TelematicsIns", Description = "Usage-based insurance product using telematics", Url = "https://telematicsins.example.com", AiSearchInfo = "telematics, insurance", AiBriefDescription = "Risk-based premiums", Industry = "Insurance", Status = "In Progress", TypeId = 2, StateId = 3 },

            new Deal { Name = "Cloud Native Data Platform", Company = "DataNative", Description = "Modern data platform for analytics and ML", Url = "https://datanative.example.com", AiSearchInfo = "data platform, cloud", AiBriefDescription = "Unified data for analytics", Industry = "Analytics", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Connected Health Devices", Company = "ConnectedHealth", Description = "Integrate medical devices with EMR", Url = "https://connectedhealth.example.com", AiSearchInfo = "devices, EMR", AiBriefDescription = "Automated device data ingestion", Industry = "Healthcare", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Retail Checkout Mobile App", Company = "MobileCheckout", Description = "Mobile checkout and digital receipts", Url = "https://mobilecheckout.example.com", AiSearchInfo = "mobile, checkout", AiBriefDescription = "Frictionless mobile checkout", Industry = "Retail", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "Digital Catalog Conversion", Company = "CatalogConvert", Description = "Convert legacy catalogs to structured data", Url = "https://catalogconvert.example.com", AiSearchInfo = "catalog, conversion", AiBriefDescription = "Structured product data for search", Industry = "E-commerce", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Predictive Sales Insights", Company = "SalePredict", Description = "Predict high-value leads using ML", Url = "https://salepredict.example.com", AiSearchInfo = "sales, ml", AiBriefDescription = "Prioritize sales outreach", Industry = "SaaS", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Fleet Electrification Study", Company = "FleetEV", Description = "Feasibility and rollout plan for EV fleet", Url = "https://fleetev.example.com", AiSearchInfo = "EV, fleet", AiBriefDescription = "Phased electrification plan", Industry = "Transport", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Customer 360 Implementation", Company = "Cust360", Description = "Build a 360 degree customer profile", Url = "https://cust360.example.com", AiSearchInfo = "customer360, integration", AiBriefDescription = "Unify customer data across systems", Industry = "Finance", Status = "Closed - Won", TypeId = 3, StateId = 5 },
            new Deal { Name = "Smart HVAC Controls", Company = "SmartHVAC", Description = "AI-driven HVAC control retrofit", Url = "https://smarthvac.example.com", AiSearchInfo = "HVAC, energy", AiBriefDescription = "Reduce HVAC energy usage", Industry = "Real Estate", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Cloud ERP Implementation", Company = "CloudERP", Description = "ERP migration to cloud", Url = "https://clouderp.example.com", AiSearchInfo = "ERP, cloud", AiBriefDescription = "Modernize financial and inventory systems", Industry = "Manufacturing", Status = "In Progress", TypeId = 3, StateId = 3 },
            new Deal { Name = "Global Localization Service", Company = "Localize", Description = "Localization and compliance for global launch", Url = "https://localize.example.com", AiSearchInfo = "localization, i18n", AiBriefDescription = "Translate and localize product", Industry = "Software", Status = "Open", TypeId = 1, StateId = 1 },

            new Deal { Name = "AI Document Understanding", Company = "DocUnderstand", Description = "Extract structured data from documents", Url = "https://docunderstand.example.com", AiSearchInfo = "nlp, ocr", AiBriefDescription = "Automate paperwork processing", Industry = "Professional Services", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Omnichannel Campaign Engine", Company = "Campaigns", Description = "Orchestrate campaigns across channels", Url = "https://campaigns.example.com", AiSearchInfo = "campaigns, omnichannel", AiBriefDescription = "Personalize across touchpoints", Industry = "Marketing", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Microlending Platform", Company = "Microlend", Description = "Platform for small loans and underwriting", Url = "https://microlend.example.com", AiSearchInfo = "lending, fintech", AiBriefDescription = "Automate underwriting for microloans", Industry = "Fintech", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Smart Retail Shelf", Company = "SmartShelf", Description = "Shelf sensors for stock and analytics", Url = "https://smartshelf.example.com", AiSearchInfo = "shelf, sensors", AiBriefDescription = "Real-time shelf visibility", Industry = "Retail", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "API Security Harden", Company = "APIHarden", Description = "Harden APIs and add threat protection", Url = "https://apiharden.example.com", AiSearchInfo = "security, api", AiBriefDescription = "Reduce attack surface", Industry = "Software", Status = "Active", TypeId = 1, StateId = 1 },
            new Deal { Name = "Autonomous Inspection Drones", Company = "InspectDrone", Description = "Drones for infrastructure inspection", Url = "https://inspectdrone.example.com", AiSearchInfo = "drone, inspection", AiBriefDescription = "Automate bridge and tower inspections", Industry = "Engineering", Status = "Closed - Won", TypeId = 3, StateId = 5 },
            new Deal { Name = "Smart Kitchen Platform", Company = "SmartKitchen", Description = "Connected kitchen devices and analytics", Url = "https://smartkitchen.example.com", AiSearchInfo = "kitchen, IoT", AiBriefDescription = "Optimize food preparation", Industry = "Hospitality", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Advanced Metering Infrastructure", Company = "AMI", Description = "Next-gen metering and analytics", Url = "https://ami.example.com", AiSearchInfo = "metering, AMI", AiBriefDescription = "Improve billing accuracy", Industry = "Energy", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Digital Twin Fleet", Company = "FleetDT", Description = "Fleet digital twin for predictive routes", Url = "https://fleetdt.example.com", AiSearchInfo = "digital twin, fleet", AiBriefDescription = "Optimize fleet performance", Industry = "Transport", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Sustainable Packaging Program", Company = "SustainPack", Description = "Transition to recyclable packaging", Url = "https://sustainpack.example.com", AiSearchInfo = "sustainability, packaging", AiBriefDescription = "Reduce plastic waste", Industry = "Manufacturing", Status = "Open", TypeId = 1, StateId = 1 },

            new Deal { Name = "Enterprise Identity Consolidation", Company = "IdConsolidate", Description = "SAML/OAuth consolidation across apps", Url = "https://idconsolidate.example.com", AiSearchInfo = "identity, SSO", AiBriefDescription = "Single identity for employees", Industry = "Software", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Precision Logistics Routing", Company = "PrecisionRoute", Description = "Optimize cross-dock and last-mile routing", Url = "https://precisionroute.example.com", AiSearchInfo = "routing, logistics", AiBriefDescription = "Faster deliveries with lower cost", Industry = "Logistics", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Retail Visual Search", Company = "VisualSearch", Description = "Visual search for product discovery", Url = "https://visualsearch.example.com", AiSearchInfo = "visual search, ecommerce", AiBriefDescription = "Find products using images", Industry = "E-commerce", Status = "Active", TypeId = 3, StateId = 2 },
            new Deal { Name = "Precision Medicine DataLake", Company = "PrecisionMed", Description = "Aggregate genomics and clinical data", Url = "https://precisionmed.example.com", AiSearchInfo = "genomics, data lake", AiBriefDescription = "Enable personalized treatment insights", Industry = "Healthcare", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "On-demand Manufacturing", Company = "OnDemandManu", Description = "On-demand parts manufacturing and fulfillment", Url = "https://ondemandmanu.example.com", AiSearchInfo = "on-demand, manufacturing", AiBriefDescription = "Short-run production on demand", Industry = "Manufacturing", Status = "Open", TypeId = 1, StateId = 1 },
            new Deal { Name = "AI Code Review Service", Company = "AICode", Description = "Automated code review and suggestions", Url = "https://aicode.example.com", AiSearchInfo = "code review, AI", AiBriefDescription = "Increase code quality", Industry = "Software", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Sustainable Fleet Retrofit", Company = "FletRetrofit", Description = "Retrofit fleet for lower emissions", Url = "https://fletretrofit.example.com", AiSearchInfo = "fleet, retrofit", AiBriefDescription = "Lower carbon footprint", Industry = "Transport", Status = "Negotiation", TypeId = 3, StateId = 4 },
            new Deal { Name = "Smart Campus Analytics", Company = "CampusAnalytics", Description = "Occupancy and energy analytics for campus", Url = "https://campusanalytics.example.com", AiSearchInfo = "campus, analytics", AiBriefDescription = "Optimize campus operations", Industry = "Education", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Automated Procurement", Company = "ProcureAuto", Description = "Procurement automation with supplier scoring", Url = "https://procureauto.example.com", AiSearchInfo = "procurement, automation", AiBriefDescription = "Reduce procurement cycle time", Industry = "Procurement", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Edge Predictive Quality", Company = "EdgeQuality", Description = "Predict product quality defects at edge", Url = "https://edgequality.example.com", AiSearchInfo = "quality, edge", AiBriefDescription = "Catch defects earlier in process", Industry = "Manufacturing", Status = "Open", TypeId = 1, StateId = 1 },

            new Deal { Name = "Pharma Regulatory Submissions", Company = "PharmaReg", Description = "Automate regulatory document generation", Url = "https://pharmareg.example.com", AiSearchInfo = "regulatory, pharma", AiBriefDescription = "Streamline submissions", Industry = "Pharma", Status = "Closed - Won", TypeId = 3, StateId = 5 },
            new Deal { Name = "AI-Powered Customer Insights", Company = "AIInsights", Description = "Uncover churn drivers using ML", Url = "https://aiinsights.example.com", AiSearchInfo = "churn, ML", AiBriefDescription = "Improve retention strategies", Industry = "SaaS", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "E-commerce Fraud Shield", Company = "FraudShield", Description = "Protect online payments from fraud", Url = "https://fraudshield.example.com", AiSearchInfo = "fraud, ecommerce", AiBriefDescription = "Reduce chargebacks", Industry = "E-commerce", Status = "In Progress", TypeId = 2, StateId = 3 },
            new Deal { Name = "Smart Fleet Telemetry", Company = "FleetTelemetry", Description = "Advanced telemetry for commercial fleets", Url = "https://fleettelemetry.example.com", AiSearchInfo = "telemetry, fleet", AiBriefDescription = "Improve uptime and routing", Industry = "Transport", Status = "Proposal", TypeId = 1, StateId = 4 },
            new Deal { Name = "Retail Price Optimization", Company = "PriceOpt", Description = "Dynamic pricing engine for retail", Url = "https://priceopt.example.com", AiSearchInfo = "pricing, optimization", AiBriefDescription = "Maximize margin with demand-aware pricing", Industry = "Retail", Status = "Active", TypeId = 2, StateId = 2 },
            new Deal { Name = "Cloud Migration Assessment", Company = "CloudAssess", Description = "Assess and plan cloud migration efforts", Url = "https://cloudassess.example.com", AiSearchInfo = "cloud, assessment", AiBriefDescription = "Reduce migration risks", Industry = "IT Services", Status = "Open", TypeId = 1, StateId = 1 }
        };

        return result;
    }
}
