// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sai.DealAssistant.Infrastructure.Persistence;

#nullable disable

namespace Sai.DealAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320182459_Deal_Company_field_added")]
    partial class Deal_Company_field_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("DealId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasDefaultValue(0u)
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiBriefDescription")
                        .HasColumnType("text");

                    b.Property<string>("AiSearchInfo")
                        .HasMaxLength(4095)
                        .HasColumnType("varchar");

                    b.Property<int?>("AmountTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .HasColumnType("citext");

                    b.Property<decimal?>("ExchangeRateToEur")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("MaxClientAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinClientAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("ProposalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasMaxLength(4095)
                        .HasColumnType("varchar");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasDefaultValue(0u)
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AmountTypeId");

                    b.HasIndex("Industry")
                        .HasDatabaseName("IX_Deals_Lower90_Industry")
                        .HasAnnotation("Npgsql:IndexExpression", "lower(left(\"Industry\", 90))");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Deals_Lower90_Name")
                        .HasAnnotation("Npgsql:IndexExpression", "lower(left(\"Name\", 90))");

                    b.HasIndex("StateId");

                    b.HasIndex("TypeId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.DealTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DealId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_DealTagss_Lower90_Tag")
                        .HasAnnotation("Npgsql:IndexExpression", "lower(left(\"Tag\", 90))");

                    b.ToTable("DealTags");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Agenda")
                        .HasColumnType("text");

                    b.Property<int?>("ContactPersonId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DealId")
                        .HasColumnType("integer");

                    b.Property<int>("Pos")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasDefaultValue(0u)
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("DealId");

                    b.HasIndex("StateId");

                    b.HasIndex("TypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.EventNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventNotes");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.AmountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("AmountTypes");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DealStates");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("DealTypes");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EventStates");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasDefaultValue(0u)
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ContactPerson", b =>
                {
                    b.HasOne("Sai.DealAssistant.Domain.Entities.Deal", "Deal")
                        .WithMany("ContactPersons")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Deal", b =>
                {
                    b.HasOne("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.AmountType", "AmountType")
                        .WithMany("Deals")
                        .HasForeignKey("AmountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealState", "State")
                        .WithMany("Deals")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealType", "Type")
                        .WithMany("Deals")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmountType");

                    b.Navigation("State");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.DealTag", b =>
                {
                    b.HasOne("Sai.DealAssistant.Domain.Entities.Deal", "Deal")
                        .WithMany("Tags")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Event", b =>
                {
                    b.HasOne("Sai.DealAssistant.Domain.Entities.ContactPerson", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId");

                    b.HasOne("Sai.DealAssistant.Domain.Entities.Deal", "Deal")
                        .WithMany("Events")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventState", "State")
                        .WithMany("Events")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventType", "Type")
                        .WithMany("Events")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactPerson");

                    b.Navigation("Deal");

                    b.Navigation("State");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.EventNote", b =>
                {
                    b.HasOne("Sai.DealAssistant.Domain.Entities.Event", "Event")
                        .WithMany("Notes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Deal", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("Events");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.Event", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.AmountType", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealState", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.DealType", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventState", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Sai.DealAssistant.Domain.Entities.ReadOnly.Enums.EventType", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
